pipeline {
  agent { 
      docker { image 'hashicorp/terraform:0.11.10' 
               args '--entrypoint="" -v $WORKSPACE:/workspace -w /workspace'
             }
  }
  stages {
    stage('TF Plan') {
       steps {

           sh 'terraform plan -out buildplan'
         }
       }
    stage('Approval') {
      steps {
        script {
          def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
        }
      }
    }
 stage('TF Apply') {
      steps {
          sh 'terraform apply -input=false buildplan'
      }
    }
  }
}
