pipeline {
  agent { label 'master'}
//  agent { 
//     docker { image 'hashicorp/terraform:0.11.10' 
//     args '--entrypoint="" -v $WORKSPACE:/workspace -w /workspace'
//        }
//      }
  stages {
//     stage('Clone') {
//       steps {
//           git credentialsId: 'github', url: 'git@github.com:rayman-g/jbox.git'
//         }
//      }
    stage('TF Plan') {
        agent { 
            docker { image 'hashicorp/terraform:0.11.10' 
            args '--entrypoint="" -v $WORKSPACE:/workspace -w /workspace'
          }
        }

       steps {
           sh 'cd test ; ls -la'
           sh 'cd test ; terraform init -input=false'
           sh 'cd test ; terraform plan -out buildplan -input=false'
         }
       }
    stage('Approval') {
      steps {
        script {
          def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
        }
      }
    }
 stage('TF Apply') {
      steps {
          sh 'cd test ; terraform apply -input=false buildplan'
      }
    }
  }
}
